package br.com.integraodonto.features;

public class FormataSqlProcedimento {

    public String FormataSqlProcedimento(long c) {

        String s = "ativo";
        String d = "nao";

        String sql = "INSERT INTO procedimento (nome, stats, consultorio, deletado)\n"
                + "VALUES\n"
                + "('Acido Hialuronico','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Ajuste de Protese','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Ajuste oclusal','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Aperto de parafuso implante','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Avaliação inicial','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Bichectomia','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Botox','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Cimentação','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Cirurgia Protocolo Inferior - 4 implantes','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Cirurgia Protocolo Superior- 6 implantes Neodent','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Cirurgia Protocolo Superior- 6 implantes Straumann','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Clareamento a laser -pacote 3 sessões','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Clareamento a laser -sessão individual','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Clareamento Caseiro','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Clareamento Misto - 2 laser e moldeiras','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Conserto protocolo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Curativo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Débito anterior','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Enxerto com biomaterial','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Enxerto de conjuntivo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Exodontia simples','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Exodontia Siso inferior','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Exodontia Siso superior','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Faceta de porcelana','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Faceta de resina','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Fechamento de implante','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Fechamento protocolo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Frenectomia','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Gel de clareamento caseiro','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Gengivectomia Por Dente','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Implante Importado','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Implante Nacional','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Lente de contato','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Mock up 6 dentes','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Mock Up dente individual','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Onlay de Cerômero','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Onlay de porcelana','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Overdenture - 2 implantes','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Overdenture -4 implantes','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Parafuso de implante','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Piercing','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Pino núcleo modelado em liga palliage','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Pino/núcleo modelado','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Placa de bruxismo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('placa de clareamento','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Polimento resinas','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Porcelana metal free','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Porcelana Metalo-cerâmica','" + s + "'," + c + ", '" + d + "'),\n"
                + "('PPR dentes importados','" + s + "'," + c + ", '" + d + "'),\n"
                + "('PPR dentes nacionais','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Profilaxia com flúor','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese Overdenture sobre dentes','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese Overdenture sobre implantes','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese parcial provisória com grampos dobráveis','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese Protocolo Inferior Neodent','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese Protocolo Inferior Straumann','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese Protocolo Superior Neodent','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese Protocolo Superior Straumann','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Prótese sobre implante','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Provisório sobre dente','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Provisório sobre implante','" + s + "'," + c + ", '" + d + "'),\n"
                + "('PT caracterizada e com palato incolor','" + s + "'," + c + ", '" + d + "'),\n"
                + "('PT dentes importados','" + s + "'," + c + ", '" + d + "'),\n"
                + "('PT dentes nacionais','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Recibo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Recobrimento radicular 1 dente','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Reembasamento prótese','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Remoção de lesão','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Reparo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Restauração de resina Grande','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Restauração de resina Pequena e Média','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Revisão protocolo','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Rx','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Selamento oclusal','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Torque na PSI','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Tratamento de canal molar','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Troca de dentes da PPR','" + s + "'," + c + ", '" + d + "'),\n"
                + "('Ulectomia','" + s + "'," + c + ", '" + d + "');";

        return sql;
    }
}
